# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(help_text='a user friendly url', max_length=60, unique=True, verbose_name='user friendly url'),
        ),
    ]
